config/routes.rb
Rails.application.routes.draw do
  
    root to: 'welcome#show'
    resources :users, controller: 'users', only: Clearance.configuration.user_actions
    
    get 'profile', to: 'welcome#index'
    get 'reporting', to: 'patients#report'
    get '/checkprice', :controller=>'patients', :action=>'checkprice'
    post '/validateprice', :controller=>'patients', :action=>'price'
    resources :patients do
	    resources :reports
	end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
    
    validates :name, presence:true
    validates :age, presence:true
    validates :phone, presence:true
    validates :ailment, presence:true
    validates :apointment, presence:true
    validates :status, presence:true
    
    belongs_to :user
    has_many :reports
    
    def to_s
        name
    end
end

app/models/report.rb
class Report < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :patient
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  
  has_many :patients
  has_many :reports
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  #Find patient only for these methods
  before_action :find_patient, only: [:show, :edit, :update, :destroy]
  #Patient needs to be logged in
  before_action :require_login

  def index
    #Ransack Search
    #Find all patients that match param q
    @search = Patient.search(params[:q])
    @patients = @search.result
    #If there is no search, show all patients that belong to that doctor.
    if params[:q].blank?
      @patients = Patient.where(:user_id => params[:user_id])
    end
  end
  
  def show
  end
  
  #Renders form for new patient
  def new
    @patient = current_user.patients.build
  end
  
  #Creates the new user.
  def create
    @patient = current_user.patients.build(patient_params)
    
    if @patient.save
      redirect_to patient_path(@patient), notice: "Patient Added"
    else
      @errors = @patient.errors.full_messages
      render :new
    end
  end
  
  #Renders edit form
  def edit
    @patient = current_user.patients.find(params[:id])
  end
  
  #Processes edit.
  def update
    @patient = current_user.patients.find(params[:id])
    
    if @patient.update_attributes(patient_params)
      redirect_to patient_path(@patient), notice: "Patient Update"
    
    else
      @errors = @patient.errors.full_messages
      render :edit
    end
  end
  
  #Deletes
  def destroy
    patient = current_user.patients.find(params[:id])
    patient.destroy
    redirect_to  patients_path, notice: "Delete Patient #{patient.name}"
  end
  
  #Renders the charts
  def report 
    render 'patients/report'
  end
  
  #Method to get the prcice for custom gem
  def price
     @input1 = params[:search_string]
     @result = Checkprice.runcheck(@input1.to_i)
  end
  
  private
    def patient_params
      params.require(:patient).permit(:name, :age, :phone, :ailment, :apointment, :status, :consultationType)
    end
    
    def find_patient
      @patient = Patient.find(params[:id])
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
    before_action :find_patient
	before_action :find_report, only: [:show, :edit, :update, :destroy]
	before_action :require_login
	
	def new
		@reports = Report.new 
	end 

	def show 
	end

	def create
		@report = Report.new(report_params)
		@report.user_id = current_user.id
		@report.patient_id = @patient.id

		if @report.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @report.update(report_params)
			redirect_to patient_path(@patient)
		else 
			render 'edit'
		end
	end

	def destroy
		@report.destroy
		redirect_to patient_path(@patient)
	end
	
	private

		def report_params
			params.require(:report).permit(:date, :report, :title)
		end

		def find_patient
			@patient = Patient.find(params[:patient_id])
		end

		def find_report
			@report = Report.find(params[:id])
		end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

private
  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    name = user_params.delete(:name)
    clinicAddresss = user_params.delete(:clinicAddresss)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.name = name
      user.clinicAddresss = clinicAddresss
  end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'welcome/index'
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Smart Health Application</title>
		<%= csrf_meta_tags %>
  
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
	  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
	  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="sorttable.js"></script>
	</head>
	<body>
<nav class="navbar navbar-expand-md navbar-bg">
  <%= link_to "Management System", root_path, class: "navbar-brand" %>

  <ul class="navbar-nav mr-auto">
    

    <% if signed_in? %> 
      <li class="nav-item"><%= link_to "Sign out", sign_out_path, method: :delete, class: "nav-link" %></li>
       
    <% else %> 
      <li class="nav-item"><%= link_to "Login", sign_in_path, class: "nav-link" %></li>
      <li class="nav-item">
        <%= link_to "Register Doctor", sign_up_path, class: "nav-link" %>
      </li>
    <% end %>
  

    <% if signed_in? %> 
      <li class="nav-item"><%= link_to "Your Patients", patients_path(user_id: current_user.id), class: "nav-link" %></li>
      <li class="nav-item">
        <a href="/profile" class="nav-link">Profile</a>
      </li>
      <li class="nav-item">
        <a href="/reporting" class="nav-link">Patient Data Overview</a>
      </li>
    <% else %> 
      <li class="nav-item"><%= link_to "Add Patient", new_patient_path, class: "nav-link" %></li>
    <% end %>
  </ul>
</nav>
 
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<% if @errors.present? %>
    <div class="errors">
        <ul>
            <%= @errors.each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">
                    <div class="text-lead h5">
                        Add Patient
                    </div>
                </div>
                <div class="card-body">
                    <%= form_for @patient do |form| %>
                    
                        <!-- Name Row-->
                        <div class="form-group row">
                            <%= form.label :name, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= form.text_field :name, :class => 'form-control' %>
                            </div>
                        </div>
                        
                        <!-- Age Row-->
                        <div class="form-group row">
                            <%= form.label :age, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= form.text_field :age, :class => 'form-control' %>
                          </div>
                        </div>
                        
                        <!-- Phone Row-->
                        <div class="form-group row">
                            <%= form.label :phone, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= form.text_field :phone, :class => 'form-control' %>
                            </div>
                        </div>
                        
                        <!-- Ailment Row -->
                        <div class="form-group row">
                            <%= form.label :ailment, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= form.text_field :ailment, :class => 'form-control' %>
                            </div>
                        </div>
                        
                        <!-- Appointment Row-->
                        <div class="form-group row">
                            <%= form.label :appointment, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= date_field(:patient, :apointment, class: "form-control") %>
                            </div>
                        </div>
                        
                        <!-- Status Row-->
                        <div class="form-group row">
                            <%= form.label :status, :class => 'col-md-3 col-form-label text-md-right' %>
                            <div class="col-md-9">
                                <%= form.select :status, 
                                    [
                                        ["Initial Consultation"], 
                                        ["Prescribed Medication"],
                                        ["Refered On"],
                                        ["Awaiting Follow Up"],
                                        ["Critical"],
                                    ],
                                    {},
                                    {class: "form-control"} 
                                %>
                            </div>
                        </div>
                        
                        <!-- Consultation Row-->
                        <div class="form-group row">
                            <%= form.label :consultationType, :class => "col-md-3 col-form-label text-md-right" %>
                            <div class="col-md-9">
                                <%= form.select :consultationType, 
                                    [
                                        ["N/A"],
                                        ["Inhouse-Clinic"],
                                        ["St.James Hospital - X-Ray"],
                                        ["Matter Private Dublin - Cardiology"],
                                        ["Matter Private Cork - Neurology"],
                                        ["Royal Eye and Ear - Ophthalmology"],
                                        ["Temple Street - Children"],
                                    ], 
                                    {},
                                    {class: "form-control"} 
                                %>
                            </div>
                        </div>
                        
                        <!-- Button Row-->
                        <div class="form-group row mb-4">
                            <div class="col-md-6 offset-md-4 mt-2">
                                <%= form.submit %>
                            </div>
                        </div>
                    <% end %>
                </div><!-- ./ CARD BODY-->
            </div> <!-- ./ CARD -->
        </div> <!-- ./ COL-8 -->
    </div> <!-- ./ ROW -->
</div> <!-- ./ Container-->

app/views/patients/edit.html.erb
<div class="text-lead h3 text-center mb-4">Edit Patient Record for <%= @patient.name %></div>

<%= render partial: "form" %>

app/views/patients/index.html.erb
<div class="container-fluid">
    <div class="text-lead text-center">
        <span class="h2 doctor-name mb-4">Dr <%= current_user.name %>'s patients</span>
        
        <%= search_form_for @search do |f| %>
            <span class="text-muted mt-4">Search by patient and/or appointment date</span>
            <div class="search-fields ml-4">
                <div class="row">
                  <div class="col-md-6">
                    <%= f.label :name_cont, "Name" %>
                  </div>
                  
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <%= f.text_field :name_cont %>
                  </div>
                </div>
                <div class="row mt-4">
                    <div class="col-md-6">
                        <%= f.submit class: "btn btn-success search-btn" %>
                    </div>
                </div>
                
            </div>
            <div>
            </div>
        <% end %>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <%= link_to "New Patient", new_patient_path, class: "btn btn-primary " %>
        </div>
    </div>
    <div class="col-md-12">
        <% if @patients.count ==0 %>
		    <center><h3>There are no patients</h3></center>
		<% else %>
            <table class="table patient-list sortable" id="patientTable">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Phone</th>
                    <th>Ailment</th>
                    <th>Apointment</th>
                    <th>Status</th>
                    <th>Hospital</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                    <% @patients.each do |patient| %>
                        <tr>
                            <td><%= link_to patient.name, patient_path(patient) %></td>
                            <td><%= patient.age %></td>
                            <td><%= patient.phone %></td>
                            <td><%= patient.ailment %></td>
                            <td><%= patient.apointment %></td>
                            <td><%= patient.status %></td>
                            <td><%= patient.consultationType %></td>
                            <td><%= link_to "Back", patients_path(user_id: current_user.id) %></td>
                            <td><%= link_to "Edit", edit_patient_path(patient)%></td>
                            <td><%= link_to( "Delete", patient_path(patient), data: {confirm: "Are you sure you want to delete: #{patient.name}?"},method: :delete) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="price">
                <div class="row">
                    <span class="text-muted">Get a price estimate</span>
                </div>
                <div class="row">
                    <%= form_tag "/validateprice" do %>
                        <%= text_field_tag :search_string, nil, :placeholder => "Level between 1 - 5" %>
                        <%= submit_tag "Check Price" %>
                    <% end %>
                </div>
            </div>
        
    <% end %>
</div>
</div>
</div>

app/views/patients/new.html.erb
<div class="text-lead h3 text-center mb-4">New Patient</div>

<%= render partial: "form" %>

app/views/patients/price.html.erb
<span class="lead text-center">The estimated price for a level <strong><%= @input1 %></strong> injury, is approximately <strong><%= @result %></strong> </span>
<hr>

<%= link_to "Back to patients", patients_path(user_id: current_user.id), class: "nav-link" %>

app/views/patients/report.html.erb
<div class="container">
    <div class="text-lead h3 text-center report-title">Overview of aggreagted patient data</div>
    <div class="row chart-labels text-muted">
        <div class="col-md-6 text-center">
            <label class="ml-1" for="patients-illness">A summary of your patients illness's</label>
        </div>
        <div class="col-md-6 text-center">
            <label for="patients-hospital">Patients Age Overview</label>
        </div>
    </div>
    <div class="row charts">
        <div class="col-md-6" id="patients-illness">
            <%= pie_chart  current_user.patients.group(:ailment).count %>
        </div>
         <div class="col-md-6" id="patients-hospital">
            <%= pie_chart  current_user.patients.group(:age).count %>
        </div>
    </div>
    <div class="row chart-labels text-muted">
        <div class="col-md-12 text-center">
            <label for="patients-status">Patients current status</label>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-12" id="patients-status">
            <%= bar_chart current_user.patients.group(:status).count, colors: ["#8506A9"] %>
        </div>
       
    </div>
  </div>
    
    
    

app/views/patients/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table class="table show-table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Phone</th>
                    <th>Ailment</th>
                    <th>Apointment</th>
                    <th>Status</th>
                    <th>Hospital</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @patient.name %></td>
                        <td><%= @patient.age %></td>
                        <td><%= @patient.phone %></td>
                        <td><%= @patient.ailment %></td>
                        <td><%= @patient.apointment %></td>
                        <td><%= @patient.status %></td>
                        <td><%= @patient.consultationType %></td>
                        <td><td><%= link_to "Transfer", edit_patient_path(@patient)%></td></td>
                        <td><%= link_to "Back", patients_path %></td>
                        <td><%= link_to "Edit", edit_patient_path(@patient)%></td>
                        <td><%= link_to( "Delete", patient_path(@patient), data: {confirm: "Are you sure you want to delete: #{@patient.name}?"},method: :delete) %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-lead text-center mt-3 mb-2">Previous Visit Reports</h3>
            <div class="report-table" align="center">
    	        <% if @patient.reports.count ==0 %>
    		        <center><h1>This patient has no medical reports on file</h1></center>
    	        <% else %>
    	        <table class="table table table-bordered table-striped show-table">
        			<thead>
        				<tr>
        			    	<th>Date</th>
        			    	<th>Title</th>
        			    	<th/>
        			  	</tr>
        			</thead>
        			<tbody>
        				<% @patient.reports.each do |report|%>
        					<tr>
        						<td><%= report.date %></td>
        						<td><%= report.title %></td>
        						<td><%= link_to "View Report", patient_report_path(report.patient.id,report.id),class: "button_one" %></td>
        					    <td><%= link_to "Edit", edit_patient_report_path(report.patient.id,report.id),class: "button_one" %></td>
			                    <td><%= link_to "Delete", patient_report_path(report.patient.id,report.id), method: :delete, data: {confirm: "Are you sure?"},class: "button_one" %></td>
        					</tr>
        				<% end %>
        			</tbody>
    		    </table>
    	    <% end %>
        	<% if signed_in? %>
                <%= link_to "Add Visit Report", new_patient_report_path(@patient),class: "button_one" %>
        	<% end %>
    	    </div>
        </div>
    </div>
</div>

app/views/reports/_form.html.erb
<% if @errors.present? %>
    <div class="errors">
        <ul>
            <%= @errors.each do |error| %>
                <li><%= error %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= simple_form_for([@patient, @patient.reports.build]) do |f| %>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">Create new report/div>
                    <div class="card-body">
                        <div class="form-group row">
                            <%= f.label :date, :class => 'col-md-3 col-form-label text-md-right' %>
                            <%= date_field(:report, :date, :class => 'col-md-4') %>
                        </div>
                         <div class="form-group row">
                            <%= f.label :title, :class => 'col-md-3 col-form-label text-md-right' %>
                            <%= f.text_field :title, :class => 'col-md-4' %>
                        </div>
                        <div class="form-group row">
                            <%= f.label :report, :class => 'col-md-3 col-form-label text-md-right' %>
                            <%= f.text_area :report, :class => 'col-md-6' %>
                        </div>
            	        <center><%= f.button :submit, :class => 'button_one'  %></center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/reports/edit.html.erb
<%= simple_form_for([@patient, @report]) do |f| %>
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">Edit Report</div>
                    <div class="card-body">
                        <div class="form-group row">
                            <%= f.label :date, :class => 'col-md-3 col-form-label text-md-right' %>
                        	<%= f.text_field :date, :input_html => {:class => 'col-md-4'} %>
                        </div>
                         <div class="form-group row">
                            <%= f.label :title, :class => 'col-md-3 col-form-label text-md-right' %>
                            <%= f.text_field :title, :class => 'col-md-4' %>
                        </div>
                        <div class="form-group row">
                            <%= f.label :report, :class => 'col-md-3 col-form-label text-md-right' %>
                            <%= f.text_area :report, :class => 'col-md-6' %>
                        </div>
            	        <center><%= f.button :submit, :class => 'button_one'  %></center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render partial: "form" %>

app/views/reports/show.html.erb
<!-- ============= CARD ============== -->
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default crd">
                <div class="card-header">Patient Report</div>
                    <div class="card-body">
                    	<!-- Patient and Ailment Label-->
			        	<div class="row">
			            	<div class="col-md-6">
			             		<label for="name" class="label">Patient Name</label>
			            	</div>
			            	<div class="col-md-6">
			              		<label for="ailment" class="label">Ailment</label>
			            	</div>
			          	</div>
			          	<!-- Patient and Ailment Data-->
          				<div class="row">
            				<div class="col-md-6 content" id="name">
				            	<%= @report.patient.name %>
				            	
				            </div>
				            <div class="col-md-6 content" id="ailment">
				            	 <%= @report.patient.ailment %>
				            </div>
				        </div>
				        <!-- Age and Status label -->
				        <div class="row mt-4">
			            	<div class="col-md-6">
			             		<label class="" for="age" class="label">Age</label>
			            	</div>
			            	<div class="col-md-6">
			              		<label for="status" class="label">Status</label>
			            	</div>
			          	</div>
			          	<!-- Patient and Ailment Data-->
          				<div class="row">
            				<div class="col-md-6 content" id="age">
				            	<%= @report.patient.age%>
				            </div>
				            <div class="col-md-6 content" id="status">
				            	 <%= @report.patient.status %>
				            </div>
				        </div>
				        
				        <!--  Date label -->
				        <div class="row mt-4">
			            	<div class="col-md-6">
			             		<label for="date" class="label">Date</label>
			            	</div>
			          	</div>
			          	
          				<div class="row">
				            <div class="col-md-12 content" id="status">
				            	 <%= @report.date %>
				            </div>
				        </div>
				        
                       <div class="row mt-4">
			            	<div class="col-md-6">
			             		<label for="report" class="label">Report</label>
			            	</div>
			          	</div>
                        <div class="row">
				            <div class="col-md-12 report" id="report">
				            	 <%= @report.report %>
				            </div>
				        </div>
                    </div>
                    <center class="link-btn">
						<%= link_to "Back", patient_path(@report.patient),class: "button_one" %>
							<% if signed_in? %>
								<% if @report.user_id == current_user.id %>
									<%= link_to "Edit", edit_patient_report_path(@report.patient_id,@report),class: "button_one" %>
									<%= link_to "Delete", patient_report_path(@report.patient_id,@report), method: :delete, data: {confirm: "Are you sure?"},class: "button_one" %>
								<% end %>
							<% end %>
					</center>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">
                    <div class="text-lead h5">
                        Sign Up
                    </div>
                </div>
                <div class="card-body">
                  
                  <div class="form-group row">
                    <%= form.label :name, :class => 'col-md-3 col-form-label text-md-right'  %>
                    <div class="col-md-9">
                      <%= form.text_field :name, type: 'text', :class => 'form-control' %>
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <%= form.label :clinicAddresss, :class => 'col-md-3 col-form-label text-md-right'  %>
                    <div class="col-md-9">
                      <%= form.text_field :clinicAddresss, type: 'text', :class => 'form-control' %>
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <%= form.label :email, :class => 'col-md-3 col-form-label text-md-right'  %>
                    <div class="col-md-9">
                      <%= form.text_field :email, type: 'email', :class => 'form-control' %>
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <%= form.label :password, :class => 'col-md-3 col-form-label text-md-right'  %>
                    <div class="col-md-9">
                      <%= form.password_field :password, :class => 'form-control' %>
                    </div>
                </div>
            </div><!-- ./ CARD BODY-->
        </div> <!-- ./ CARD -->
    </div> <!-- ./ COL-8 -->
  </div> <!-- ./ ROW -->
</div> <!-- ./ Container-->


              

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class="text-lead h3 text-center mb-4"><%= t(".title") %></div>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
      
      <div class="form-group row mb-4">
        <div class="col-md-6 offset-md-4 mt-2">
          <%= form.submit %>
          <%= link_to t(".sign_in"), sign_in_path %>
        </div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Profile for Dr <%=  current_user.name %></h1>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Clinic Address</th>
        <th>Email</th>
        <th>Client's</th>
    </thead>
    <tbody>
        <td><%= current_user.id %></td>
        <td><%= current_user.name %></td>
        <td><%= current_user.clinicAddresss %></td>
        <td><%= current_user.email %></td>
        <td><%= current_user.patients.count %></td>
    </tbody>
</table>

app/views/welcome/show.html.erb
<div class="card">
  <h5 class="card-header text-center">Welcome to the Clinics Patient Management System</h5>
  <div class="card-body text-center">
      <% if signed_in? %>
        <h5 class="card-title">Welcome <strong>Dr. <%= current_user.name %></strong></h5>
        <h5 class="card-title">Please proceed to your patients overview page</h5>
        <span class="text-muted"><%= link_to "Your Patients", patients_path(user_id: current_user.id) %></span>
      <% else %>
      <h5 class="card-title"><%= link_to "Please Login", sign_in_path, class: "nav-link" %></h5>
      <% end %>
    <p class="card-text mt-4">Have a good day.</p>
  </div>
</div>